name: lint

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: check out Git repository
        uses: actions/checkout@v2
      - name: black
        uses: lgeiger/black-action@v1.0.1
        with:
          args: . --check